name: test_app_sql
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  flutter_bloc: ^8.1.5
  flutter_staggered_animations: ^1.1.1
  image_picker: ^0.8.7
  get_it: ^7.2.0
  injectable: ^1.5.3
  modal_bottom_sheet: ^3.0.0-pre
  equatable: ^2.0.5
  #Data Base
  product_models:
    path: packages/product_models
  product_repository:
      path: packages/product_repositories
  product_services:
    path: packages/product_services

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  injectable_generator: ^1.5.4

flutter:

  uses-material-design: true

  assets:
    - assets/graphics/
