name: product_services
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8
  path_provider: ^2.1.3
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


